# Bundles the modular app into ONE self-contained HTML file (no Node required).
#   - inlines every local stylesheet (<link rel="stylesheet" href="css/...">), in order
#   - inlines every <script src="..."> in document order
#   - embeds each brand image once (window.VJP_ASSETS, resolved by VJP.ui.asset)
#     and the favicon as a data: URI
#   - keeps the Google Fonts <link>: online it loads Inter / IBM Plex Mono,
#     offline the system-font fallbacks in css/styles.css apply
# Output: dist/index.html  (works via file:// double-click and offline).
# Usage:  powershell -NoProfile -ExecutionPolicy Bypass -File build-inline.ps1
param([string]$OutDir = "dist", [string]$OutName = "index.html")
$ErrorActionPreference = 'Stop'
$app = Split-Path -Parent $MyInvocation.MyCommand.Path
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Read-Text([string]$rel) {
    $path = Join-Path $app $rel
    if (-not (Test-Path $path -PathType Leaf)) { throw "Missing file referenced by index.html: $rel" }
    return [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
}
function Get-DataUri([string]$rel) {
    $path = Join-Path $app $rel
    if (-not (Test-Path $path -PathType Leaf)) { throw "Missing asset: $rel" }
    $mime = @{ '.png' = 'image/png'; '.svg' = 'image/svg+xml'; '.jpg' = 'image/jpeg'; '.webp' = 'image/webp' }[[System.IO.Path]::GetExtension($rel).ToLower()]
    return "data:$mime;base64," + [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($path))
}
# Inline text must not close its own element early.
function Assert-Inlinable([string]$rel, [string]$text, [string]$tag) {
    if ($text -match "(?i)</$tag") { throw "$rel contains '</$tag' and cannot be inlined safely" }
}

$html = Read-Text 'index.html'

# 1. local stylesheets (remote ones, i.e. Google Fonts, stay as links)
$html = [regex]::Replace($html, '<link rel="stylesheet" href="((?!https?:)[^"]+)">', [System.Text.RegularExpressions.MatchEvaluator] {
    param($m)
    $rel = $m.Groups[1].Value; $css = Read-Text $rel
    Assert-Inlinable $rel $css 'style'
    "<style>`n/* ===== $rel ===== */`n$css`n</style>"
})

# 2. scripts, in document order
$html = [regex]::Replace($html, '<script src="([^"]+)"></script>', [System.Text.RegularExpressions.MatchEvaluator] {
    param($m)
    $rel = $m.Groups[1].Value; $js = Read-Text $rel
    Assert-Inlinable $rel $js 'script'
    "<script>`n/* ===== $rel ===== */`n$js`n</script>"
})

# 3. images: favicon as data URI; every brand image named in the code, once, in VJP_ASSETS
$html = [regex]::Replace($html, 'href="(brand/[^"]+\.svg)"', [System.Text.RegularExpressions.MatchEvaluator] { param($m) 'href="' + (Get-DataUri $m.Groups[1].Value) + '"' })
$names = [regex]::Matches($html, "asset\('(brand/[^']+)'\)") | ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique
$entries = $names | ForEach-Object { "  '" + $_ + "': '" + (Get-DataUri $_) + "'" }
$assets = "<script>`n/* ===== embedded images (resolved by VJP.ui.asset) ===== */`nwindow.VJP_ASSETS = {`n" + ($entries -join ",`n") + "`n};`n</script>`n"
$i = $html.IndexOf('</head>')
if ($i -lt 0) { throw 'index.html has no </head>' }
$html = $html.Insert($i, $assets)

# leftovers would be broken in a standalone file:
#   relative src/href in the page markup, or image paths the code uses without VJP.ui.asset
$skeleton = [regex]::Replace($html, '(?s)<(script|style)>.*?</\1>', '')
$left = [regex]::Matches($skeleton, '(?:src|href)="((?!https?:|data:|#)[^"]+)"') | ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique
if ($left) { throw ("Unresolved relative references in index.html: " + ($left -join ', ')) }
$probe = [regex]::Replace($html.Replace($assets, ''), "asset\('brand/[^']+'\)", '')
$raw = [regex]::Matches($probe, 'brand/[\w.-]+\.(?:png|svg|jpg|webp)') | ForEach-Object { $_.Value } | Sort-Object -Unique
if ($raw) { throw ("Image paths not routed through VJP.ui.asset: " + ($raw -join ', ')) }

$stamp = "<!-- Single-file build of the Venturi Jet Pump Design Studio - generated by build-inline.ps1 on " + (Get-Date -Format 'yyyy-MM-dd HH:mm') + ". Edit the modular sources, not this file. -->`n"
$html = $html.Insert($html.IndexOf('<html'), $stamp)

$dist = Join-Path $app $OutDir
if (-not (Test-Path $dist)) { New-Item -ItemType Directory -Path $dist | Out-Null }
$out = Join-Path $dist $OutName
[System.IO.File]::WriteAllText($out, $html, $utf8)
$kb = [math]::Round((Get-Item $out).Length / 1KB)
Write-Output "$out  ($kb KB; $($names.Count) embedded images)"
